#server:
#  port: 8081

spring:
    profile: prod
    datasource:
      url: jdbc:mysql://localhost:3306/usuario
      username: root
      password: sandoval

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true