server:
   port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuario2
    username: root
    password: sandoval

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma usuario"
#appVersion: "1.0.0"

#//LOS ESPACIOS ENTRE ETIQUETAS SON MUY IMPORTANTES