#server:
#  port: 8081

spring:
    profile: prod
    datasource:
      url: jdbc:mysql://database-plazoleta.cs2p2calnqse.us-east-2.rds.amazonaws.com:3306/usuario
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: admin
      password: sandoval

#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true