
server:
   port: 8085

spring:
  application:
    name: usuario-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/usuario2
#    username: root
#    password: sandoval
  profiles:
        active: prod

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#eureka:
##  client:
##    fetch-registry: false
##    register-with-eureka: false
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:

  profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/usuario
    username: root
    password: sandoval

---
spring:

  profile: prueba
  datasource:
    url: jdbc:mysql://localhost:3306/usuario2
    username: root
    password: sandoval

appDescription: "Pragma usuario"
#appVersion: "1.0.0"

#//LOS ESPACIOS ENTRE ETIQUETAS SON MUY IMPORTANTES