#spring.application.name=servicio-plazoleta
#server.port=8082
##eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#
#
#spring.datasource.url=jdbc:mysql://localhost:3306/plazoleta
#spring.datasource.username=root
#spring.datasource.password=sandoval
##mostramos las sentencias sql en consola que se ejecutan
#spring.jpa.show-sql=true
##evitamos que las tablas y datos se eliminen.
#spring.jpa.hibernate.ddl-auto=update


server:
  port: 8082

spring:
  application:
    name: plazoleta-service
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  #  client:
  #    fetch-registry: false
  #    register-with-eureka: false
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

appDescription: "Pragma usuario"

---
spring:

  profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta2
    username: root
    password: sandoval

#appVersion: "1.0.0"

#//LOS ESPACIOS ENTRE ETIQUETAS SON MUY IMPORTANTES